dataset: cifar10n
data_path: ./dataset
num_classes: 10
img_size: 32
noise_type: ins
noise_ratio: random_label1

model: resnet34
lr: 0.02
momentum: 0.9
weight_decay: 0.001
batch_size: 128
epochs: 250
average_entropy_loss: True
noise_matrix_scale: 0.25
vol_lambda: 0.0001

alpha: 1
beta: 6
lam: 1.0
lam_consist: 1
balance_lam: 0.2

seed: 42
wandb: False
