dataset: cifar10
data_path: ./dataset
num_classes: 14
img_size: 224
noise_type: ins
noise_ratio: 1.0

model: resnet50_pretrained
lr: 0.002
momentum: 0.9
weight_decay: 0.001
batch_size: 64
epochs: 15
average_entropy_loss: True
noise_matrix_scale: 0.5
vol_lambda: 0.0001

alpha: 1
beta: 28
lam: 1.0
lam_consist: 3
balance_lam: 0.1

seed: 42
wandb: False
