dataset: webvision
data_path: .data/
num_classes: 50
img_size: 299
noise_type: ins
noise_ratio: 1.0
crop_ratio: 0.95

model: inception_resnet_v2
lr: 0.02
momentum: 0.9
weight_decay: 0.0005
batch_size: 64
epochs: 100
average_entropy_loss: True
noise_matrix_scale: 2.2
vol_lambda: 0.001

alpha: 2
beta: 200
lam: 1.0
lam_consist: 3
balance_lam: 0.1

seed: 42
wandb: False
